In [4]:
# EDA - Data Import and Export


# Import required libraries
import pandas as pd
import sqlite3

# Load the EV Adoption dataset
df = pd.read_csv("ev_sales_by_makers_and_cat_15-24.csv")

# Display the complete dataset
print("===== DATASET =====")
display(df)

# Display first five records
print("\n===== FIRST FIVE ROWS =====")
display(df.head())

# Display last five records
print("\n===== LAST FIVE ROWS =====")
display(df.tail())

# Display dataset information
print("\n===== DATASET INFORMATION =====")
df.info()

# Display statistical summary
print("\n===== STATISTICAL SUMMARY =====")
display(df.describe(include='all'))

# Display dataset shape
print("\nDataset Shape:")
print(df.shape)

# Display column names
print("\nColumns:")
print(df.columns)

# Check missing values
print("\n===== MISSING VALUES =====")
print(df.isnull().sum())

# Export dataset to CSV
df.to_csv("ev_adoption_export.csv", index=False)
print("\nCSV file exported successfully!")

# Export dataset to Excel
df.to_excel("ev_adoption_export.xlsx", index=False)
print("Excel file exported successfully!")

# Create SQLite database
conn = sqlite3.connect("ev_adoption.db")

# Export DataFrame to SQL table
df.to_sql(
    "ev_adoption",
    conn,
    if_exists="replace",
    index=False
)

print("Dataset exported successfully to SQLite database!")

# Close the connection
conn.close()

===== DATASET =====

,Cat,Maker,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,3W,"""VOLVO GROUP INDIA PVT LTD""",0,0,31,12,0,0,0,0,0,0
1,3W,3EV INDUSTRIES PVT LTD,0,0,0,0,0,0,112,390,545,51
2,2W,3GB TECHNOLOGY PVT LTD,0,0,0,1,0,0,0,0,0,0
3,3W,3GB TECHNOLOGY PVT LTD,0,1,1,0,0,0,0,0,0,0
4,3W,3S INDUSTRIES PRIVATE LIMITED,0,0,0,0,48,66,43,68,266,578
...,...,...,...,...,...,...,...,...,...,...,...,...
1381,2W,ZHEJIANG LUYUAN (IMPORTER: DYNAM EV TECH),0,0,0,0,0,0,0,21,45,9
1382,2W,ZHEJIANG TIANYING (IMPORTER: NEWTRON ELECTRIC),0,0,0,0,0,0,0,0,64,6
1383,2W,ZHONGHUALONG (IMPORTER: POWORO PVT LTD),0,0,0,0,0,0,0,0,0,54
1384,2W,ZHONGXING (IMPORTER:GREENO AUTOMOBILE),0,0,0,0,0,0,0,0,0,5
1385,3W,ZOHAN TRADERS AND BIG METRO,0,0,0,0,0,0,0,5,131,74

===== FIRST FIVE ROWS =====

,Cat,Maker,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,3W,"""VOLVO GROUP INDIA PVT LTD""",0,0,31,12,0,0,0,0,0,0
1,3W,3EV INDUSTRIES PVT LTD,0,0,0,0,0,0,112,390,545,51
2,2W,3GB TECHNOLOGY PVT LTD,0,0,0,1,0,0,0,0,0,0
3,3W,3GB TECHNOLOGY PVT LTD,0,1,1,0,0,0,0,0,0,0
4,3W,3S INDUSTRIES PRIVATE LIMITED,0,0,0,0,48,66,43,68,266,578

===== LAST FIVE ROWS =====

,Cat,Maker,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
1381,2W,ZHEJIANG LUYUAN (IMPORTER: DYNAM EV TECH),0,0,0,0,0,0,0,21,45,9
1382,2W,ZHEJIANG TIANYING (IMPORTER: NEWTRON ELECTRIC),0,0,0,0,0,0,0,0,64,6
1383,2W,ZHONGHUALONG (IMPORTER: POWORO PVT LTD),0,0,0,0,0,0,0,0,0,54
1384,2W,ZHONGXING (IMPORTER:GREENO AUTOMOBILE),0,0,0,0,0,0,0,0,0,5
1385,3W,ZOHAN TRADERS AND BIG METRO,0,0,0,0,0,0,0,5,131,74

===== DATASET INFORMATION =====
<class 'pandas.DataFrame'>
RangeIndex: 1386 entries, 0 to 1385
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Cat     1386 non-null   str
 1   Maker   1386 non-null   str
 2   2015    1386 non-null   int64
 3   2016    1386 non-null   int64
 4   2017    1386 non-null   int64
 5   2018    1386 non-null   int64
 6   2019    1386 non-null   int64
 7   2020    1386 non-null   int64
 8   2021    1386 non-null   int64
 9   2022    1386 non-null   int64
 10  2023    1386 non-null   int64
 11  2024    1386 non-null   int64
dtypes: int64(10), str(2)
memory usage: 130.1 KB

===== STATISTICAL SUMMARY =====

,Cat,Maker,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
count,1386,1386,1386.000000,1386.000000,1386.000000,1386.000000,1386.000000,1386.000000,1386.000000,1386.000000,1386.000000,1386.000000
unique,4,1196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,3W,OTHERS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,866,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,5.593074,35.533189,62.784271,93.624098,119.614719,89.300144,237.268398,736.315296,1103.343434,706.308081
std,NaN,NaN,62.430741,400.757230,496.932817,511.486338,692.529043,504.744348,1793.878376,5917.016908,9631.219039,7022.251339
min,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000
75%,NaN,NaN,0.000000,0.000000,3.000000,6.000000,10.000000,7.000000,13.000000,39.000000,96.000000,79.000000
max,NaN,NaN,1708.000000,13401.000000,15094.000000,10816.000000,13213.000000,9543.000000,46260.000000,109398.000000,267355.000000,211273.000000

Dataset Shape:
(1386, 12)

Columns:
Index(['Cat', 'Maker', '2015', '2016', '2017', '2018', '2019', '2020', '2021',
       '2022', '2023', '2024'],
      dtype='str')

===== MISSING VALUES =====
Cat      0
Maker    0
2015     0
2016     0
2017     0
2018     0
2019     0
2020     0
2021     0
2022     0
2023     0
2024     0
dtype: int64

CSV file exported successfully!
Excel file exported successfully!
Dataset exported successfully to SQLite database!

In [5]:
import pandas as pd

# Load EV Adoption dataset
df = pd.read_csv("ev_sales_by_makers_and_cat_15-24.csv")

print("===== DATASET INFO =====")
df.info()

print("\n===== MISSING VALUES IN EACH COLUMN =====")
print(df.isnull().sum())

print("\n===== TOTAL MISSING VALUES =====")
print(df.isnull().sum().sum())

print("\n===== ANY MISSING VALUES? =====")
print(df.isnull().values.any())

print("\n===== NON-MISSING VALUES COUNT =====")
print(df.notnull().sum())

===== DATASET INFO =====
<class 'pandas.DataFrame'>
RangeIndex: 1386 entries, 0 to 1385
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Cat     1386 non-null   str
 1   Maker   1386 non-null   str
 2   2015    1386 non-null   int64
 3   2016    1386 non-null   int64
 4   2017    1386 non-null   int64
 5   2018    1386 non-null   int64
 6   2019    1386 non-null   int64
 7   2020    1386 non-null   int64
 8   2021    1386 non-null   int64
 9   2022    1386 non-null   int64
 10  2023    1386 non-null   int64
 11  2024    1386 non-null   int64
dtypes: int64(10), str(2)
memory usage: 130.1 KB

===== MISSING VALUES IN EACH COLUMN =====
Cat      0
Maker    0
2015     0
2016     0
2017     0
2018     0
2019     0
2020     0
2021     0
2022     0
2023     0
2024     0
dtype: int64

===== TOTAL MISSING VALUES =====
0

===== ANY MISSING VALUES? =====
False

===== NON-MISSING VALUES COUNT =====
Cat      1386
Maker    1386
2015     1386
2016     1386
2017     1386
2018     1386
2019     1386
2020     1386
2021     1386
2022     1386
2023     1386
2024     1386
dtype: int64

In [6]:
# Identify numerical EV sales columns
year_columns = [
    '2015',
    '2016',
    '2017',
    '2018',
    '2019',
    '2020',
    '2021',
    '2022',
    '2023',
    '2024'
]

# Ensure EV sales columns are numeric
for column in year_columns:
    df[column] = pd.to_numeric(
        df[column],
        errors='coerce'
    )


# Fill all missing values with 0
df_constant = df.fillna(0)

print("===== CONSTANT VALUE =====")
display(df_constant.head())


# Fill numerical EV sales columns with mean
df_mean = df.copy()

for column in year_columns:
    df_mean[column] = df_mean[column].fillna(
        df_mean[column].mean()
    )

print("\n===== MEAN =====")
display(df_mean.head())


# Fill numerical EV sales columns with median
df_median = df.copy()

for column in year_columns:
    df_median[column] = df_median[column].fillna(
        df_median[column].median()
    )

print("\n===== MEDIAN =====")
display(df_median.head())


# Fill Maker column with mode
df_mode = df.copy()

df_mode["Maker"] = df_mode["Maker"].fillna(
    df_mode["Maker"].mode()[0]
)

print("\n===== MODE =====")
display(df_mode.head())


# Forward Fill
df_ffill = df.ffill()

print("\n===== FORWARD FILL =====")
display(df_ffill.head())


# Backward Fill
df_bfill = df.bfill()

print("\n===== BACKWARD FILL =====")
display(df_bfill.head())

===== CONSTANT VALUE =====

,Cat,Maker,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,3W,"""VOLVO GROUP INDIA PVT LTD""",0,0,31,12,0,0,0,0,0,0
1,3W,3EV INDUSTRIES PVT LTD,0,0,0,0,0,0,112,390,545,51
2,2W,3GB TECHNOLOGY PVT LTD,0,0,0,1,0,0,0,0,0,0
3,3W,3GB TECHNOLOGY PVT LTD,0,1,1,0,0,0,0,0,0,0
4,3W,3S INDUSTRIES PRIVATE LIMITED,0,0,0,0,48,66,43,68,266,578

===== MEAN =====

,Cat,Maker,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,3W,"""VOLVO GROUP INDIA PVT LTD""",0,0,31,12,0,0,0,0,0,0
1,3W,3EV INDUSTRIES PVT LTD,0,0,0,0,0,0,112,390,545,51
2,2W,3GB TECHNOLOGY PVT LTD,0,0,0,1,0,0,0,0,0,0
3,3W,3GB TECHNOLOGY PVT LTD,0,1,1,0,0,0,0,0,0,0
4,3W,3S INDUSTRIES PRIVATE LIMITED,0,0,0,0,48,66,43,68,266,578

===== MEDIAN =====

,Cat,Maker,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,3W,"""VOLVO GROUP INDIA PVT LTD""",0,0,31,12,0,0,0,0,0,0
1,3W,3EV INDUSTRIES PVT LTD,0,0,0,0,0,0,112,390,545,51
2,2W,3GB TECHNOLOGY PVT LTD,0,0,0,1,0,0,0,0,0,0
3,3W,3GB TECHNOLOGY PVT LTD,0,1,1,0,0,0,0,0,0,0
4,3W,3S INDUSTRIES PRIVATE LIMITED,0,0,0,0,48,66,43,68,266,578

===== MODE =====

,Cat,Maker,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,3W,"""VOLVO GROUP INDIA PVT LTD""",0,0,31,12,0,0,0,0,0,0
1,3W,3EV INDUSTRIES PVT LTD,0,0,0,0,0,0,112,390,545,51
2,2W,3GB TECHNOLOGY PVT LTD,0,0,0,1,0,0,0,0,0,0
3,3W,3GB TECHNOLOGY PVT LTD,0,1,1,0,0,0,0,0,0,0
4,3W,3S INDUSTRIES PRIVATE LIMITED,0,0,0,0,48,66,43,68,266,578

===== FORWARD FILL =====

,Cat,Maker,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,3W,"""VOLVO GROUP INDIA PVT LTD""",0,0,31,12,0,0,0,0,0,0
1,3W,3EV INDUSTRIES PVT LTD,0,0,0,0,0,0,112,390,545,51
2,2W,3GB TECHNOLOGY PVT LTD,0,0,0,1,0,0,0,0,0,0
3,3W,3GB TECHNOLOGY PVT LTD,0,1,1,0,0,0,0,0,0,0
4,3W,3S INDUSTRIES PRIVATE LIMITED,0,0,0,0,48,66,43,68,266,578

===== BACKWARD FILL =====

,Cat,Maker,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,3W,"""VOLVO GROUP INDIA PVT LTD""",0,0,31,12,0,0,0,0,0,0
1,3W,3EV INDUSTRIES PVT LTD,0,0,0,0,0,0,112,390,545,51
2,2W,3GB TECHNOLOGY PVT LTD,0,0,0,1,0,0,0,0,0,0
3,3W,3GB TECHNOLOGY PVT LTD,0,1,1,0,0,0,0,0,0,0
4,3W,3S INDUSTRIES PRIVATE LIMITED,0,0,0,0,48,66,43,68,266,578

In [7]:
# Final Missing Value Check

print("===== FINAL DATASET CHECK =====")

print("\nDataset Shape:")
print(df.shape)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nTotal Missing Values:")
print(df.isnull().sum().sum())

print("\nEV Adoption Data Import and Missing Value Handling Completed Successfully!")

===== FINAL DATASET CHECK =====

Dataset Shape:
(1386, 12)

Missing Values:
Cat      0
Maker    0
2015     0
2016     0
2017     0
2018     0
2019     0
2020     0
2021     0
2022     0
2023     0
2024     0
dtype: int64

Total Missing Values:
0

EV Adoption Data Import and Missing Value Handling Completed Successfully!