In [1]:
# EX NO: 3 - Data Cleaning


import pandas as pd

# Load dataset
df = pd.read_csv("ev_sales_by_makers_and_cat_15-24.csv")

# CHECK MISSING VALUES

print("===== DATASET INFO ====")
df.info()

print("\n===== MISSING VALUES IN EACH COLUMN ====")
print(df.isnull().sum())

print("\n===== TOTAL MISSING VALUES ====")
print(df.isnull().sum().sum())

print("\n===== ANY MISSING VALUES? ====")
print(df.isnull().values.any())

print("\n===== NON-MISSING VALUES COUNT ====")
print(df.notnull().sum())


# FILL MISSING VALUES


# Fill all missing values with 0
df_constant = df.fillna(0)
print("\n===== CONSTANT VALUE ====")
display(df_constant.head())

# Fill '2024' column with mean
df_mean = df.copy()
df_mean["2024"] = df_mean["2024"].fillna(df_mean["2024"].mean())

print("\n===== MEAN ====")
display(df_mean.head())

# Fill '2024' column with median
df_median = df.copy()
df_median["2024"] = df_median["2024"].fillna(df_median["2024"].median())

print("\n===== MEDIAN ====")
display(df_median.head())

# Fill 'Maker' column with mode
df_mode = df.copy()
df_mode["Maker"] = df_mode["Maker"].fillna(df_mode["Maker"].mode()[0])

print("\n===== MODE ====")
display(df_mode.head())

# Forward Fill
df_ffill = df.ffill()

print("\n===== FORWARD FILL ====")
display(df_ffill.head())

# Backward Fill
df_bfill = df.bfill()

print("\n===== BACKWARD FILL ====")
display(df_bfill.head())



# DROP MISSING VALUES


# Drop rows with missing values
df_drop_rows = df.dropna()

print("\n===== DROP ROWS ====")
display(df_drop_rows.head())

# Drop columns with missing values
df_drop_cols = df.dropna(axis=1)

print("\n===== DROP COLUMNS ====")
display(df_drop_cols.head())

# Drop rows having any missing value
df_any = df.dropna(how="any")

print("\n===== DROP HOW='ANY' ====")
display(df_any.head())

# Drop rows where all values are missing
df_all = df.dropna(how="all")

print("\n===== DROP HOW='ALL' ====")
display(df_all.head())

# Keep rows with at least 5 non-null values
df_thresh = df.dropna(thresh=5)

print("\n===== THRESH = 5 ====")
display(df_thresh.head())

# Drop rows where 'Maker' or 'Cat' is missing
df_subset = df.dropna(subset=["Maker", "Cat"])

print("\n===== SUBSET (Maker, Cat) ====")
display(df_subset.head())

# Drop missing values permanently
df_copy = df.copy()
df_copy.dropna(inplace=True)

print("\n===== AFTER inplace=True ====")
display(df_copy.head())

===== DATASET INFO ====
<class 'pandas.DataFrame'>
RangeIndex: 1386 entries, 0 to 1385
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Cat     1386 non-null   str
 1   Maker   1386 non-null   str
 2   2015    1386 non-null   int64
 3   2016    1386 non-null   int64
 4   2017    1386 non-null   int64
 5   2018    1386 non-null   int64
 6   2019    1386 non-null   int64
 7   2020    1386 non-null   int64
 8   2021    1386 non-null   int64
 9   2022    1386 non-null   int64
 10  2023    1386 non-null   int64
 11  2024    1386 non-null   int64
dtypes: int64(10), str(2)
memory usage: 130.1 KB

===== MISSING VALUES IN EACH COLUMN ====
Cat      0
Maker    0
2015     0
2016     0
2017     0
2018     0
2019     0
2020     0
2021     0
2022     0
2023     0
2024     0
dtype: int64

===== TOTAL MISSING VALUES ====
0

===== ANY MISSING VALUES? ====
False

===== NON-MISSING VALUES COUNT ====
Cat      1386
Maker    1386
2015     1386
2016     1386
2017     1386
2018     1386
2019     1386
2020     1386
2021     1386
2022     1386
2023     1386
2024     1386
dtype: int64

===== CONSTANT VALUE ====

,Cat,Maker,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,3W,"""VOLVO GROUP INDIA PVT LTD""",0,0,31,12,0,0,0,0,0,0
1,3W,3EV INDUSTRIES PVT LTD,0,0,0,0,0,0,112,390,545,51
2,2W,3GB TECHNOLOGY PVT LTD,0,0,0,1,0,0,0,0,0,0
3,3W,3GB TECHNOLOGY PVT LTD,0,1,1,0,0,0,0,0,0,0
4,3W,3S INDUSTRIES PRIVATE LIMITED,0,0,0,0,48,66,43,68,266,578

===== MEAN ====

,Cat,Maker,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,3W,"""VOLVO GROUP INDIA PVT LTD""",0,0,31,12,0,0,0,0,0,0
1,3W,3EV INDUSTRIES PVT LTD,0,0,0,0,0,0,112,390,545,51
2,2W,3GB TECHNOLOGY PVT LTD,0,0,0,1,0,0,0,0,0,0
3,3W,3GB TECHNOLOGY PVT LTD,0,1,1,0,0,0,0,0,0,0
4,3W,3S INDUSTRIES PRIVATE LIMITED,0,0,0,0,48,66,43,68,266,578

===== MEDIAN ====

,Cat,Maker,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,3W,"""VOLVO GROUP INDIA PVT LTD""",0,0,31,12,0,0,0,0,0,0
1,3W,3EV INDUSTRIES PVT LTD,0,0,0,0,0,0,112,390,545,51
2,2W,3GB TECHNOLOGY PVT LTD,0,0,0,1,0,0,0,0,0,0
3,3W,3GB TECHNOLOGY PVT LTD,0,1,1,0,0,0,0,0,0,0
4,3W,3S INDUSTRIES PRIVATE LIMITED,0,0,0,0,48,66,43,68,266,578

===== MODE ====

,Cat,Maker,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,3W,"""VOLVO GROUP INDIA PVT LTD""",0,0,31,12,0,0,0,0,0,0
1,3W,3EV INDUSTRIES PVT LTD,0,0,0,0,0,0,112,390,545,51
2,2W,3GB TECHNOLOGY PVT LTD,0,0,0,1,0,0,0,0,0,0
3,3W,3GB TECHNOLOGY PVT LTD,0,1,1,0,0,0,0,0,0,0
4,3W,3S INDUSTRIES PRIVATE LIMITED,0,0,0,0,48,66,43,68,266,578

===== FORWARD FILL ====

,Cat,Maker,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,3W,"""VOLVO GROUP INDIA PVT LTD""",0,0,31,12,0,0,0,0,0,0
1,3W,3EV INDUSTRIES PVT LTD,0,0,0,0,0,0,112,390,545,51
2,2W,3GB TECHNOLOGY PVT LTD,0,0,0,1,0,0,0,0,0,0
3,3W,3GB TECHNOLOGY PVT LTD,0,1,1,0,0,0,0,0,0,0
4,3W,3S INDUSTRIES PRIVATE LIMITED,0,0,0,0,48,66,43,68,266,578

===== BACKWARD FILL ====

,Cat,Maker,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,3W,"""VOLVO GROUP INDIA PVT LTD""",0,0,31,12,0,0,0,0,0,0
1,3W,3EV INDUSTRIES PVT LTD,0,0,0,0,0,0,112,390,545,51
2,2W,3GB TECHNOLOGY PVT LTD,0,0,0,1,0,0,0,0,0,0
3,3W,3GB TECHNOLOGY PVT LTD,0,1,1,0,0,0,0,0,0,0
4,3W,3S INDUSTRIES PRIVATE LIMITED,0,0,0,0,48,66,43,68,266,578

===== DROP ROWS ====

,Cat,Maker,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,3W,"""VOLVO GROUP INDIA PVT LTD""",0,0,31,12,0,0,0,0,0,0
1,3W,3EV INDUSTRIES PVT LTD,0,0,0,0,0,0,112,390,545,51
2,2W,3GB TECHNOLOGY PVT LTD,0,0,0,1,0,0,0,0,0,0
3,3W,3GB TECHNOLOGY PVT LTD,0,1,1,0,0,0,0,0,0,0
4,3W,3S INDUSTRIES PRIVATE LIMITED,0,0,0,0,48,66,43,68,266,578

===== DROP COLUMNS ====

,Cat,Maker,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,3W,"""VOLVO GROUP INDIA PVT LTD""",0,0,31,12,0,0,0,0,0,0
1,3W,3EV INDUSTRIES PVT LTD,0,0,0,0,0,0,112,390,545,51
2,2W,3GB TECHNOLOGY PVT LTD,0,0,0,1,0,0,0,0,0,0
3,3W,3GB TECHNOLOGY PVT LTD,0,1,1,0,0,0,0,0,0,0
4,3W,3S INDUSTRIES PRIVATE LIMITED,0,0,0,0,48,66,43,68,266,578

===== DROP HOW='ANY' ====

,Cat,Maker,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,3W,"""VOLVO GROUP INDIA PVT LTD""",0,0,31,12,0,0,0,0,0,0
1,3W,3EV INDUSTRIES PVT LTD,0,0,0,0,0,0,112,390,545,51
2,2W,3GB TECHNOLOGY PVT LTD,0,0,0,1,0,0,0,0,0,0
3,3W,3GB TECHNOLOGY PVT LTD,0,1,1,0,0,0,0,0,0,0
4,3W,3S INDUSTRIES PRIVATE LIMITED,0,0,0,0,48,66,43,68,266,578

===== DROP HOW='ALL' ====

,Cat,Maker,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,3W,"""VOLVO GROUP INDIA PVT LTD""",0,0,31,12,0,0,0,0,0,0
1,3W,3EV INDUSTRIES PVT LTD,0,0,0,0,0,0,112,390,545,51
2,2W,3GB TECHNOLOGY PVT LTD,0,0,0,1,0,0,0,0,0,0
3,3W,3GB TECHNOLOGY PVT LTD,0,1,1,0,0,0,0,0,0,0
4,3W,3S INDUSTRIES PRIVATE LIMITED,0,0,0,0,48,66,43,68,266,578

===== THRESH = 5 ====

,Cat,Maker,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,3W,"""VOLVO GROUP INDIA PVT LTD""",0,0,31,12,0,0,0,0,0,0
1,3W,3EV INDUSTRIES PVT LTD,0,0,0,0,0,0,112,390,545,51
2,2W,3GB TECHNOLOGY PVT LTD,0,0,0,1,0,0,0,0,0,0
3,3W,3GB TECHNOLOGY PVT LTD,0,1,1,0,0,0,0,0,0,0
4,3W,3S INDUSTRIES PRIVATE LIMITED,0,0,0,0,48,66,43,68,266,578

===== SUBSET (Maker, Cat) ====

,Cat,Maker,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,3W,"""VOLVO GROUP INDIA PVT LTD""",0,0,31,12,0,0,0,0,0,0
1,3W,3EV INDUSTRIES PVT LTD,0,0,0,0,0,0,112,390,545,51
2,2W,3GB TECHNOLOGY PVT LTD,0,0,0,1,0,0,0,0,0,0
3,3W,3GB TECHNOLOGY PVT LTD,0,1,1,0,0,0,0,0,0,0
4,3W,3S INDUSTRIES PRIVATE LIMITED,0,0,0,0,48,66,43,68,266,578

===== AFTER inplace=True ====

,Cat,Maker,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,3W,"""VOLVO GROUP INDIA PVT LTD""",0,0,31,12,0,0,0,0,0,0
1,3W,3EV INDUSTRIES PVT LTD,0,0,0,0,0,0,112,390,545,51
2,2W,3GB TECHNOLOGY PVT LTD,0,0,0,1,0,0,0,0,0,0
3,3W,3GB TECHNOLOGY PVT LTD,0,1,1,0,0,0,0,0,0,0
4,3W,3S INDUSTRIES PRIVATE LIMITED,0,0,0,0,48,66,43,68,266,578